### PR TITLE
- use Vista style for FolderBrowserDialog 

### PR DESCRIPTION
**Pull request by MagicAndre1981**
use Vista style for FolderBrowserDialog instead of the old one

### CODE REVIEW

**Comment by MagicAndre1981** [comment]
hm, this is my first Git Pull request, maybe I missed something. Add the files from here: 

http://www.lyquidity.com/devblog/?p=136

**Comment by pocorall** [comment]
It is not built as it is. Please move these files to SCM_Notifier directory, add these files into visual studio project, and make a pull request again.

**Comment by MagicAndre1981** [comment]
I had the files in a folder FolderSelect, but when I try to add them to the solution, the VS copies them into the SCM_Notifier directory and adds them, but those files are not added to git. This causes your issue.

How can I add commit https://github.com/MagicAndre1981/scm-notifier/commit/46cff2194bee6bbfa0f4131155cd9d1a04fe37cd to this pull request?

**Comment by pocorall** [comment]
It works finally ;-D

**Comment by MagicAndre1981** [comment]
I think it can be removed, because updating to 4.5 should also use the Vista dialogs

**Comment by pocorall** [comment]
Agree. Simpler is better.

**Pull request merged**
